### ISSUE TITLE
Idea

### ISSUE THREAD

**Issue by sam05kerr** [TheGR1D/GR1D#5]
I think that one of us should create a code on github which tests our knowkedge on our revision and other subjects

**Comment by HarryBrookes** [comment]
Yeah that's a great idea but to use it effectively scale into our older years. this is a great idea that i believe we can take forward so its a really helpful tool for revision in the future. I will assign some people to this task which i believe Sam can head up, if you need any help come and ask me or Ben in person or via email.

Thanks All 

Harry Brookes,
Founder of The GR1D
